/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2022-01-04 13:17:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Utils.RequestUtils;
import models.carrito;
import models.coment;
import Utils.requestUP;
import models.products;
import java.util.List;

public final class objetodetalle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("models.products");
    _jspx_imports_classes.add("Utils.RequestUtils");
    _jspx_imports_classes.add("Utils.requestUP");
    _jspx_imports_classes.add("models.carrito");
    _jspx_imports_classes.add("models.coment");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("        \n");
      out.write("            \n");
      out.write("                ");
//@page import="models.usuer"
      out.write("\n");
      out.write("                    \n");
      out.write("                        \n");
      out.write("                            ");

                            //List<usuer> users = (List<usuer>)request.getAttribute(RequestUtils.KEY_ALL_USERS);
                            //List<usuer> users = (List<usuer>)request.getAttribute("ShowUsers");
                            List<products> prods = (List<products>)request.getAttribute(requestUP.KEY_ALL_Prods);
                            List<coment> come = (List<coment>)request.getAttribute(requestUP.KEY_ALL_COMN);
                            List<carrito> carrs = (List<carrito>)request.getAttribute(RequestUtils.KEY_ALL_CARR);
                            
      out.write("\n");
      out.write("\n");
      out.write("                                <!doctype html>\n");
      out.write("                                <html lang=\"en\">\n");
      out.write("\n");
      out.write("                                <head>\n");
      out.write("                                    <!-- Required meta tags -->\n");
      out.write("                                    <meta charset=\"utf-8\">\n");
      out.write("                                    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("                                    <!-- Bootstrap CSS -->\n");
      out.write("                                    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\n");
      out.write("                                    <title>Producto | Detalle</title>\n");
      out.write("                                </head>\n");
      out.write("\n");
      out.write("                                <body>\n");
      out.write("                                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Uname", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("fer", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("                                    ");

                                    HttpSession mySession = request.getSession();
                                    String name2 = (String)mySession.getAttribute("jes");
                                    String name1 = (String)mySession.getAttribute("gar");
                                    Integer name3 = (Integer)mySession.getAttribute("jes2");
                                    //byte[] name3 = (byte[])mySession.getAttribute("img");
                                    
      out.write("\n");
      out.write("                                        ");
 int ida=0; 
      out.write("\n");
      out.write("                                            <div class=\"row\" style=\"padding-left:20px; padding-top:20px; padding-right:20px; padding-bottom:20px;\">\n");
      out.write("                                                <div>\n");
      out.write("                                                    \n");
      out.write("                                                    <div class=\"container-fluid\">\n");
      out.write("                                                    <div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-ride=\"carousel\" style=\" margin: auto; height: 300px;width: 300px; padding-top: 15px ; padding-bottom: 15px ;\">\n");
      out.write("                                                    <ol class=\"carousel-indicators\">\n");
      out.write("                                                        <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("                                                        <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\n");
      out.write("                                                        <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>\n");
      out.write("                                                    </ol>\n");
      out.write("                                                    <div class=\"carousel-inner\">\n");
      out.write("                                                        \n");
      out.write("                                                        ");

                                                    //for(usuer user : users){
                                                    int vid = prods.size();
                                                    int act=0;  
                                                    for(products prod : prods){
                                                    int idp= prod.getIdprod();
                                                    if(vid-1!=act&&vid!=0){
                                                        if(act==0){
                                                    
      out.write("\n");
      out.write("                                                    <div class=\"carousel-item active \" >\n");
      out.write("                                                    <img src=\"");
      out.print(prod.getPimg());
      out.write("\" alt=\"...\" height=\"300\" width=\"300px\" class=\"img-thumbnail\">\n");
      out.write("                                                    </div>\n");
      out.write("                                                    ");
 
                                                        }else{
      out.write("\n");
      out.write("                                                        <div class=\"carousel-item\">\n");
      out.write("                                                        <img src=\"");
      out.print(prod.getPimg());
      out.write("\" alt=\"...\" height=\"300\" width=\"300px\" class=\"img-thumbnail\">\n");
      out.write("                                                        </div>\n");
      out.write("                                                        ");
}} else { 
      out.write("\n");
      out.write("                                                            <div class=\"carousel-item\">\n");
      out.write("                                                            <iframe height=\"300\" width=\"300\" src=\"");
      out.print(prod.getPimg());
      out.write("\"> </iframe>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        ");
 }act++; }
      out.write("\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"prev\">\n");
      out.write("                                                        <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("                                                        <span class=\"sr-only\">Previous</span>\n");
      out.write("                                                    </a>\n");
      out.write("                                                    <a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"next\" style=\"\">\n");
      out.write("                                                        <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("                                                        <span class=\"sr-only\">Next</span>\n");
      out.write("                                                    </a>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    \n");
      out.write("                                                    </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    ");
 //  for(usuer user : users){
                                            for(products prod : prods){
                                            int idp= prod.getIdprod();
                                            
      out.write("\n");
      out.write("                                                        <div class=\"col\">\n");
      out.write("                                                            ");
 if(ida!=idp){ 
      out.write("\n");
      out.write("                                                                <b>Producto: </b>\n");
      out.write("                                                                ");
      out.print( prod.getNombre() );
      out.write("<br>\n");
      out.write("                                                                    <b>Categoria: </b>\n");
      out.write("                                                                    ");
      out.print( prod.getCatego() );
      out.write("<br>\n");
      out.write("                                                                        <b>Descripción: </b>\n");
      out.write("                                                                        ");
      out.print(prod.getDescri() );
      out.write("\n");
      out.write("                                                                            ");
 ida=idp; }
      out.write("<br>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        ");
 } 
      out.write("\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                            \n");
      out.write("                                            <div class=\"container-fluid\" style=\"\">\n");
      out.write("                                                <form name=\"log\" method=\"POST\" action=\"addcarr?prod=");
      out.print(ida);
      out.write("\">\n");
      out.write("                                                    <div class=\"form-group col-md-4\" id=\"cate\">\n");
      out.write("                                                        <select id=\"inputState\" class=\"form-control\" name=\"TPP\">\n");
      out.write("                                                            <option selected value=\"1\">Paypal</option>\n");
      out.write("                                                            <option value=\"2\">Efectivo</option>\n");
      out.write("                                                            <option value=\"3\">Debito/Credito</option>\n");
      out.write("                                                            <option value=\"4\">Monedero Virtual</option>\n");
      out.write("                                                            <option value=\"5\">Pendiente</option>\n");
      out.write("                                                        </select>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"input-group mb-3\">\n");
      out.write("                                                        <input type=\"number\" class=\"form-control\" placeholder=\"cantidad\" aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\" name=\"cat\">\n");
      out.write("                                                        <div class=\"input-group-append\">\n");
      out.write("                                                            <input class=\"form-control\" type=\"submit\" value=\"Enviar propuesta\" name=\"Subir\" id=\"boton\">\n");
      out.write("                                                            ");
      out.write("\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </form>\n");
      out.write("                                                <div>\n");
      out.write("                                                    <hr style=\"border: 10px solid blue; border-radius: 5px;\">\n");
      out.write("                                                </div>\n");
      out.write("                                                ");
 if(carrs.size()>0){ 
      out.write("\n");
      out.write("                                                <h2>Mi Opinión</h2>\n");
      out.write("                                                    <form name=\"logos\" method=\"POST\" action=\"opinoin?prod=");
      out.print(ida);
      out.write("\">\n");
      out.write("                                                        <div class=\"input-group mb-3\">\n");
      out.write("                                                            <input type=\"number\" class=\"form-control\" placeholder=\"valoracion\" aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\" name=\"val\">\n");
      out.write("                                                            <input type=\"Text\" class=\"form-control\" placeholder=\"opinion del producto\" aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\" name=\"opc\">\n");
      out.write("                                                            <div class=\"input-group-append\">\n");
      out.write("                                                                <input class=\"form-control\" type=\"submit\" value=\"Comentar\" name=\"Subir\" id=\"boton\">\n");
      out.write("                                                                ");
      out.write("\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </form>\n");
      out.write("                                                <div>\n");
      out.write("                                                    <hr style=\"border: 10px solid blue; border-radius: 5px;\">\n");
      out.write("                                                </div>\n");
      out.write("                                                    ");
} for(coment CM : come){ 
      out.write(" <br>\n");
      out.write("                                                        <div class=\"card\">\n");
      out.write("                                                            <div class=\"card-header\">\n");
      out.write("                                                                <b>Usuario: </b>");
      out.print(CM.getUname());
      out.write("\n");
      out.write("                                                                    ");
      out.print(CM.getUape());
      out.write("\n");
      out.write("                                                            </div>\n");
      out.write("                                                            <div class=\"card-body\">\n");
      out.write("                                                                <h5 class=\"card-title\">Calificación:\n");
      out.write("                                                                    ");
      out.print(CM.getVal());
      out.write("\n");
      out.write("                                                                </h5>\n");
      out.write("                                                                <p class=\"card-text\">\n");
      out.write("                                                                    <b>Opinión: </b>");
      out.print(CM.getCome());
      out.write("\n");
      out.write("                                                                </p>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        ");
 } 
      out.write("\n");
      out.write("                                            </div>\n");
      out.write("                                            <!-- Optional JavaScript -->\n");
      out.write("                                            <!-- jQuery first, then Popper.js, then Bootstrap JS -->\n");
      out.write("                                            <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\n");
      out.write("                                            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\n");
      out.write("                                            <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\n");
      out.write("                                </body>\n");
      out.write("\n");
      out.write("                                </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
